/* ==========================================================================
   UPLIFT — Single-file bundler
   --------------------------------------------------------------------------
   Develop across multiple files; present from one. Inlines every stylesheet
   and script (including the vendored Three.js) into one self-contained HTML
   file that runs from a double-click, offline, with no server.

       node build.js

   Output: dist/uplift-presentation.html
   ========================================================================== */

const fs = require("fs");
const path = require("path");

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), "utf8");

let html = read("index.html");

// --- Inline stylesheets ---------------------------------------------------
html = html.replace(/<link rel="stylesheet" href="([^"]+)">/g, (m, href) => {
  console.log("  css  " + href);
  return "<style>\n" + read(href) + "\n</style>";
});

// --- Inline scripts -------------------------------------------------------
html = html.replace(/<script src="([^"]+)"><\/script>/g, (m, src) => {
  if (/^https?:\/\//.test(src)) return m;   // leave remote scripts alone
  console.log("  js   " + src);
  return "<script>\n" + read(src) + "\n</script>";
});

// --- Note in the source ---------------------------------------------------
html = html.replace(
  "<head>",
  "<head>\n<!-- Built by build.js — single self-contained file. Edit the multi-file\n" +
  "     source and re-run `node build.js`; do not edit this file directly. -->"
);

fs.mkdirSync(path.join(root, "dist"), { recursive: true });
const out = path.join(root, "dist", "uplift-presentation.html");
fs.writeFileSync(out, html);

const kb = (fs.statSync(out).size / 1024).toFixed(0);
console.log("\n  → dist/uplift-presentation.html  (" + kb + " KB)");
console.log("  Fonts still load from Google Fonts; the page falls back to system");
console.log("  serif/sans if the venue is offline. Everything else is embedded.");
